/* Generated By:JavaCC: Do not edit this line. Proj6Constants.java */
package project6;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Proj6Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGNORE = 1;
  /** RegularExpression Id. */
  int SGL_COMMENT = 10;
  /** RegularExpression Id. */
  int COMMENT = 11;
  /** RegularExpression Id. */
  int ASSIGNMENT_STATEMENT = 12;
  /** RegularExpression Id. */
  int EXPRESSION = 13;
  /** RegularExpression Id. */
  int MULT_COMMENT = 14;
  /** RegularExpression Id. */
  int MATH_SYMBOL = 15;
  /** RegularExpression Id. */
  int RESERVED = 16;
  /** RegularExpression Id. */
  int STRING = 17;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 18;
  /** RegularExpression Id. */
  int INTEGER = 19;
  /** RegularExpression Id. */
  int REAL = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;
  /** RegularExpression Id. */
  int UPPER = 23;
  /** RegularExpression Id. */
  int DIGITS = 24;
  /** RegularExpression Id. */
  int LOWER = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int DECIMAL = 28;
  /** RegularExpression Id. */
  int OCTAL = 29;
  /** RegularExpression Id. */
  int HEXIDECIMAL = 30;
  /** RegularExpression Id. */
  int NODEC = 31;
  /** RegularExpression Id. */
  int NOEXP = 32;
  /** RegularExpression Id. */
  int BOTH = 33;
  /** RegularExpression Id. */
  int SPEC = 34;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PREPROCESSOR_OUTPUT = 1;
  /** Lexical state. */
  int INSIDE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IGNORE>",
    "\"#\"",
    "\"\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "<SGL_COMMENT>",
    "<COMMENT>",
    "<ASSIGNMENT_STATEMENT>",
    "<EXPRESSION>",
    "<MULT_COMMENT>",
    "<MATH_SYMBOL>",
    "<RESERVED>",
    "<STRING>",
    "<SPECIAL_SYMBOL>",
    "<INTEGER>",
    "<REAL>",
    "<CHAR>",
    "<IDENTIFIER>",
    "<UPPER>",
    "<DIGITS>",
    "<LOWER>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL>",
    "<OCTAL>",
    "<HEXIDECIMAL>",
    "<NODEC>",
    "<NOEXP>",
    "<BOTH>",
    "<SPEC>",
    "\"+\"",
  };

}
