/* Generated By:JavaCC: Do not edit this line. Proj6TokenManager.java */
package project6;
import java.io.*;

/** Token Manager. */
public class Proj6TokenManager implements Proj6Constants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x10L) != 0L)
            return 237;
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 8;
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 43:
         return jjStopAtPos(0, 8);
      case 47:
         return jjMoveStringLiteralDfa1_0(0x10L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(1, 4, 238);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 427;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 237:
                  if (curChar == 47)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 16)
                        kind = 16;
                     jjCheckNAdd(401);
                  }
                  else if ((0x100100002400L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if ((0x2c0000000000L & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if (curChar == 47)
                     jjAddStates(0, 1);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 34;
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(31, 32);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAddStates(2, 17);
                  }
                  else if (curChar == 48)
                     jjAddStates(18, 33);
                  if (curChar == 48)
                  {
                     if (kind > 11)
                        kind = 11;
                     jjCheckNAddStates(34, 49);
                  }
                  break;
               case 1:
                  if ((0x2c0000000000L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 30:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 31:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 32:
                  if (curChar == 34 && kind > 10)
                     kind = 10;
                  break;
               case 33:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 35:
                  if (curChar == 39 && kind > 13)
                     kind = 13;
                  break;
               case 169:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(50, 51);
                  break;
               case 170:
                  if (curChar == 61)
                     jjCheckNAddStates(52, 55);
                  break;
               case 172:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(56, 61);
                  break;
               case 173:
                  if (curChar == 59 && kind > 3)
                     kind = 3;
                  break;
               case 174:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(62, 73);
                  break;
               case 175:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(175, 176);
                  break;
               case 176:
                  if (curChar == 46)
                     jjAddStates(74, 76);
                  break;
               case 177:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(178, 179);
                  break;
               case 178:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(178, 179);
                  break;
               case 180:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(77, 79);
                  break;
               case 181:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(80, 85);
                  break;
               case 182:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(80, 85);
                  break;
               case 183:
                  if (curChar == 48)
                     jjCheckNAddStates(86, 97);
                  break;
               case 184:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(184, 176);
                  break;
               case 185:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(185, 186);
                  break;
               case 186:
                  if (curChar == 46)
                     jjAddStates(98, 100);
                  break;
               case 187:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(101, 106);
                  break;
               case 188:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(101, 106);
                  break;
               case 189:
                  if (curChar == 48)
                     jjAddStates(107, 114);
                  break;
               case 191:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(191, 176);
                  break;
               case 194:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(194, 186);
                  break;
               case 197:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(197, 198);
                  break;
               case 199:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(115, 117);
                  break;
               case 200:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(118, 123);
                  break;
               case 201:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(118, 123);
                  break;
               case 202:
                  if (curChar == 48)
                     jjCheckNAddStates(124, 129);
                  break;
               case 203:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(124, 129);
                  break;
               case 204:
                  if (curChar == 48)
                     jjAddStates(130, 131);
                  break;
               case 206:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(132, 137);
                  break;
               case 210:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(138, 143);
                  break;
               case 212:
                  if (curChar == 48)
                     jjCheckNAddStates(144, 149);
                  break;
               case 213:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(144, 149);
                  break;
               case 214:
                  if (curChar == 48)
                     jjAddStates(150, 151);
                  break;
               case 216:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(152, 157);
                  break;
               case 218:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(218, 198);
                  break;
               case 219:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(158, 163);
                  break;
               case 220:
                  if (curChar == 48)
                     jjCheckNAddStates(164, 169);
                  break;
               case 221:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(164, 169);
                  break;
               case 222:
                  if (curChar == 48)
                     jjAddStates(170, 171);
                  break;
               case 224:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(172, 177);
                  break;
               case 226:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(227, 179);
                  break;
               case 227:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(227, 179);
                  break;
               case 228:
                  if (curChar == 48)
                     jjAddStates(178, 179);
                  break;
               case 230:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(230, 179);
                  break;
               case 232:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(232, 186);
                  break;
               case 233:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(233, 198);
                  break;
               case 234:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(180, 185);
                  break;
               case 235:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 236:
                  if (curChar == 47)
                     jjAddStates(0, 1);
                  break;
               case 238:
                  jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 239:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 240:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 47 && kind > 8)
                     kind = 8;
                  break;
               case 242:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(2, 17);
                  break;
               case 243:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(186, 188);
                  break;
               case 244:
                  if ((0x2c0000000000L & l) != 0L)
                     jjCheckNAddStates(189, 191);
                  break;
               case 245:
                  if (curChar == 48)
                     jjCheckNAddStates(192, 201);
                  break;
               case 246:
                  if (curChar == 47)
                     jjCheckNAddStates(189, 191);
                  break;
               case 247:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(202, 211);
                  break;
               case 248:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 249:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(212, 215);
                  break;
               case 250:
                  if (curChar == 59 && kind > 2)
                     kind = 2;
                  break;
               case 251:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(251, 252);
                  break;
               case 252:
                  if (curChar == 46)
                     jjAddStates(216, 218);
                  break;
               case 253:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(254, 255);
                  break;
               case 254:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(254, 255);
                  break;
               case 256:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(219, 221);
                  break;
               case 257:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(222, 225);
                  break;
               case 258:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(222, 225);
                  break;
               case 259:
                  if (curChar == 48)
                     jjCheckNAddStates(226, 229);
                  break;
               case 260:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(226, 229);
                  break;
               case 261:
                  if (curChar == 48)
                     jjAddStates(230, 231);
                  break;
               case 263:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(232, 235);
                  break;
               case 265:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(266, 255);
                  break;
               case 266:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(266, 255);
                  break;
               case 267:
                  if (curChar == 48)
                     jjAddStates(236, 237);
                  break;
               case 269:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(269, 255);
                  break;
               case 271:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(271, 272);
                  break;
               case 272:
                  if (curChar == 46)
                     jjAddStates(238, 240);
                  break;
               case 273:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(241, 244);
                  break;
               case 274:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(241, 244);
                  break;
               case 275:
                  if (curChar == 48)
                     jjCheckNAddStates(245, 248);
                  break;
               case 276:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(245, 248);
                  break;
               case 277:
                  if (curChar == 48)
                     jjAddStates(249, 250);
                  break;
               case 279:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(251, 254);
                  break;
               case 281:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(281, 282);
                  break;
               case 283:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(255, 257);
                  break;
               case 284:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(258, 261);
                  break;
               case 285:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(258, 261);
                  break;
               case 286:
                  if (curChar == 48)
                     jjCheckNAddStates(262, 265);
                  break;
               case 287:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(262, 265);
                  break;
               case 288:
                  if (curChar == 48)
                     jjAddStates(266, 267);
                  break;
               case 290:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(268, 271);
                  break;
               case 292:
                  if (curChar == 48)
                     jjAddStates(272, 279);
                  break;
               case 294:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(280, 283);
                  break;
               case 297:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(297, 252);
                  break;
               case 300:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(300, 272);
                  break;
               case 303:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(303, 282);
                  break;
               case 305:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(284, 287);
                  break;
               case 306:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(306, 252);
                  break;
               case 307:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(307, 272);
                  break;
               case 308:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(308, 282);
                  break;
               case 309:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(309, 310);
                  break;
               case 310:
                  if (curChar == 46)
                     jjAddStates(288, 290);
                  break;
               case 311:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(312, 313);
                  break;
               case 312:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(312, 313);
                  break;
               case 314:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(291, 293);
                  break;
               case 315:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(294, 296);
                  break;
               case 316:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(294, 296);
                  break;
               case 317:
                  if (curChar == 48)
                     jjCheckNAddStates(297, 299);
                  break;
               case 318:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(297, 299);
                  break;
               case 319:
                  if (curChar == 48)
                     jjAddStates(300, 301);
                  break;
               case 321:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(302, 304);
                  break;
               case 323:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(324, 313);
                  break;
               case 324:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(324, 313);
                  break;
               case 325:
                  if (curChar == 48)
                     jjAddStates(305, 306);
                  break;
               case 327:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(327, 313);
                  break;
               case 329:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(329, 330);
                  break;
               case 330:
                  if (curChar == 46)
                     jjAddStates(307, 309);
                  break;
               case 331:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(310, 312);
                  break;
               case 332:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(310, 312);
                  break;
               case 333:
                  if (curChar == 48)
                     jjCheckNAddStates(313, 315);
                  break;
               case 334:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(313, 315);
                  break;
               case 335:
                  if (curChar == 48)
                     jjAddStates(316, 317);
                  break;
               case 337:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(318, 320);
                  break;
               case 339:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(339, 340);
                  break;
               case 341:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(321, 323);
                  break;
               case 342:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(324, 326);
                  break;
               case 343:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(324, 326);
                  break;
               case 344:
                  if (curChar == 48)
                     jjCheckNAddStates(327, 329);
                  break;
               case 345:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(327, 329);
                  break;
               case 346:
                  if (curChar == 48)
                     jjAddStates(330, 331);
                  break;
               case 348:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(332, 334);
                  break;
               case 350:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(350);
                  break;
               case 351:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(351, 352);
                  break;
               case 353:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(335, 337);
                  break;
               case 354:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(355);
                  break;
               case 355:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(355);
                  break;
               case 356:
                  if (curChar != 48)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(357);
                  break;
               case 357:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(357);
                  break;
               case 358:
                  if (curChar == 48)
                     jjAddStates(338, 339);
                  break;
               case 360:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 360;
                  break;
               case 362:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(362, 363);
                  break;
               case 363:
                  if (curChar == 46)
                     jjAddStates(340, 342);
                  break;
               case 364:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(365);
                  break;
               case 365:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(365);
                  break;
               case 366:
                  if (curChar != 48)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(367);
                  break;
               case 367:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(367);
                  break;
               case 368:
                  if (curChar == 48)
                     jjAddStates(343, 344);
                  break;
               case 370:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 370;
                  break;
               case 372:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(372, 373);
                  break;
               case 373:
                  if (curChar == 46)
                     jjAddStates(345, 347);
                  break;
               case 374:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(375, 376);
                  break;
               case 375:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(375, 376);
                  break;
               case 377:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(348, 350);
                  break;
               case 378:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(379);
                  break;
               case 379:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(379);
                  break;
               case 380:
                  if (curChar != 48)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(381);
                  break;
               case 381:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(381);
                  break;
               case 382:
                  if (curChar == 48)
                     jjAddStates(351, 352);
                  break;
               case 384:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 384;
                  break;
               case 386:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(387, 376);
                  break;
               case 387:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(387, 376);
                  break;
               case 388:
                  if (curChar == 48)
                     jjAddStates(353, 354);
                  break;
               case 390:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(390, 376);
                  break;
               case 392:
                  if (curChar != 48)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAddStates(34, 49);
                  break;
               case 393:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(355, 357);
                  break;
               case 394:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(394, 310);
                  break;
               case 395:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(395, 330);
                  break;
               case 396:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(396, 340);
                  break;
               case 397:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(397);
                  break;
               case 398:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(398, 352);
                  break;
               case 399:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(399, 363);
                  break;
               case 400:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(400, 373);
                  break;
               case 401:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 16)
                     kind = 16;
                  jjCheckNAdd(401);
                  break;
               case 402:
                  if (curChar == 48)
                     jjAddStates(18, 33);
                  break;
               case 404:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(358, 360);
                  break;
               case 407:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(407, 310);
                  break;
               case 410:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(410, 330);
                  break;
               case 413:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(413, 340);
                  break;
               case 416:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjstateSet[jjnewStateCnt++] = 416;
                  break;
               case 419:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(419, 352);
                  break;
               case 422:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(422, 363);
                  break;
               case 425:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(425, 373);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 14)
                        kind = 14;
                     jjCheckNAddStates(361, 363);
                  }
                  else if (curChar == 95)
                     jjAddStates(364, 366);
                  if (curChar == 118)
                     jjAddStates(367, 368);
                  else if (curChar == 117)
                     jjAddStates(369, 370);
                  else if (curChar == 115)
                     jjAddStates(371, 376);
                  else if (curChar == 114)
                     jjAddStates(377, 379);
                  else if (curChar == 105)
                     jjCheckNAddStates(380, 382);
                  else if (curChar == 102)
                     jjAddStates(383, 384);
                  else if (curChar == 101)
                     jjAddStates(385, 387);
                  else if (curChar == 100)
                     jjCheckNAddStates(388, 390);
                  else if (curChar == 99)
                     jjAddStates(391, 394);
                  else if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 28;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 23;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 9;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 2:
                  if (curChar == 111 && kind > 9)
                     kind = 9;
                  break;
               case 3:
               case 11:
                  if (curChar == 116)
                     jjCheckNAdd(2);
                  break;
               case 4:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 107 && kind > 9)
                     kind = 9;
                  break;
               case 7:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 12:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 103 && kind > 9)
                     kind = 9;
                  break;
               case 15:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 102 && kind > 9)
                     kind = 9;
                  break;
               case 19:
                  if (curChar == 101)
                     jjCheckNAdd(18);
                  break;
               case 20:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 101 && kind > 9)
                     kind = 9;
                  break;
               case 26:
               case 79:
               case 162:
                  if (curChar == 108)
                     jjCheckNAdd(25);
                  break;
               case 27:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 31:
                  jjAddStates(395, 396);
                  break;
               case 34:
                  if ((0x7fffffe17fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 36:
                  if (curChar == 95)
                     jjAddStates(364, 366);
                  break;
               case 37:
                  if (curChar == 108 && kind > 9)
                     kind = 9;
                  break;
               case 38:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 120 && kind > 9)
                     kind = 9;
                  break;
               case 42:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 121 && kind > 9)
                     kind = 9;
                  break;
               case 49:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 99)
                     jjAddStates(391, 394);
                  break;
               case 58:
               case 84:
                  if (curChar == 115)
                     jjCheckNAdd(25);
                  break;
               case 59:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 114 && kind > 9)
                     kind = 9;
                  break;
               case 61:
                  if (curChar == 97)
                     jjCheckNAdd(60);
                  break;
               case 62:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if (curChar == 116 && kind > 9)
                     kind = 9;
                  break;
               case 64:
                  if (curChar == 115)
                     jjCheckNAdd(63);
                  break;
               case 65:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if (curChar == 117)
                     jjCheckNAdd(25);
                  break;
               case 68:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 100)
                     jjCheckNAddStates(388, 390);
                  break;
               case 74:
                  if (curChar == 108)
                     jjCheckNAdd(63);
                  break;
               case 75:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 80:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 101)
                     jjAddStates(385, 387);
                  break;
               case 85:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 109 && kind > 9)
                     kind = 9;
                  break;
               case 87:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 110 && kind > 9)
                     kind = 9;
                  break;
               case 90:
               case 118:
                  if (curChar == 114)
                     jjCheckNAdd(89);
                  break;
               case 91:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 102)
                     jjAddStates(383, 384);
                  break;
               case 95:
                  if (curChar == 97)
                     jjCheckNAdd(63);
                  break;
               case 96:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 111)
                     jjCheckNAdd(60);
                  break;
               case 99:
                  if (curChar == 105)
                     jjCheckNAddStates(380, 382);
                  break;
               case 100:
                  if (curChar == 110)
                     jjCheckNAdd(25);
                  break;
               case 101:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 110)
                     jjCheckNAdd(63);
                  break;
               case 105:
                  if (curChar == 114)
                     jjAddStates(377, 379);
                  break;
               case 106:
                  if (curChar == 101)
                     jjCheckNAdd(60);
                  break;
               case 107:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
               case 140:
                  if (curChar == 99)
                     jjCheckNAdd(63);
                  break;
               case 113:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 119:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 115)
                     jjAddStates(371, 376);
                  break;
               case 123:
                  if (curChar == 114)
                     jjCheckNAdd(63);
                  break;
               case 124:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 100 && kind > 9)
                     kind = 9;
                  break;
               case 127:
               case 153:
                  if (curChar == 101)
                     jjCheckNAdd(126);
                  break;
               case 128:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 111)
                     jjCheckNAdd(18);
                  break;
               case 132:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 99 && kind > 9)
                     kind = 9;
                  break;
               case 136:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 141:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 104 && kind > 9)
                     kind = 9;
                  break;
               case 145:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar == 117)
                     jjAddStates(369, 370);
                  break;
               case 150:
                  if (curChar == 111)
                     jjCheckNAdd(89);
                  break;
               case 151:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 154:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 118)
                     jjAddStates(367, 368);
                  break;
               case 160:
                  if (curChar == 105)
                     jjCheckNAdd(126);
                  break;
               case 161:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 163:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddStates(361, 363);
                  break;
               case 169:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(169, 170);
                  break;
               case 171:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(56, 61);
                  break;
               case 172:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(56, 61);
                  break;
               case 179:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(397, 400);
                  break;
               case 190:
                  if (curChar == 120)
                     jjCheckNAdd(191);
                  break;
               case 191:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(191, 176);
                  break;
               case 192:
                  if (curChar == 88)
                     jjCheckNAdd(191);
                  break;
               case 193:
                  if (curChar == 120)
                     jjCheckNAdd(194);
                  break;
               case 194:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(194, 186);
                  break;
               case 195:
                  if (curChar == 88)
                     jjCheckNAdd(194);
                  break;
               case 196:
                  if (curChar == 120)
                     jjCheckNAdd(197);
                  break;
               case 197:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(197, 198);
                  break;
               case 198:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(401, 404);
                  break;
               case 205:
                  if (curChar == 120)
                     jjCheckNAdd(206);
                  break;
               case 206:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(132, 137);
                  break;
               case 207:
                  if (curChar == 88)
                     jjCheckNAdd(206);
                  break;
               case 208:
                  if (curChar == 88)
                     jjCheckNAdd(197);
                  break;
               case 209:
                  if (curChar == 120)
                     jjCheckNAdd(210);
                  break;
               case 210:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(138, 143);
                  break;
               case 211:
                  if (curChar == 88)
                     jjCheckNAdd(210);
                  break;
               case 215:
                  if (curChar == 120)
                     jjCheckNAdd(216);
                  break;
               case 216:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(152, 157);
                  break;
               case 217:
                  if (curChar == 88)
                     jjCheckNAdd(216);
                  break;
               case 223:
                  if (curChar == 120)
                     jjCheckNAdd(224);
                  break;
               case 224:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(172, 177);
                  break;
               case 225:
                  if (curChar == 88)
                     jjCheckNAdd(224);
                  break;
               case 229:
                  if (curChar == 120)
                     jjCheckNAdd(230);
                  break;
               case 230:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(230, 179);
                  break;
               case 231:
                  if (curChar == 88)
                     jjCheckNAdd(230);
                  break;
               case 235:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(235);
                  break;
               case 238:
                  jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 255:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(405, 408);
                  break;
               case 262:
                  if (curChar == 120)
                     jjCheckNAdd(263);
                  break;
               case 263:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(232, 235);
                  break;
               case 264:
                  if (curChar == 88)
                     jjCheckNAdd(263);
                  break;
               case 268:
                  if (curChar == 120)
                     jjCheckNAdd(269);
                  break;
               case 269:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(269, 255);
                  break;
               case 270:
                  if (curChar == 88)
                     jjCheckNAdd(269);
                  break;
               case 278:
                  if (curChar == 120)
                     jjCheckNAdd(279);
                  break;
               case 279:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(251, 254);
                  break;
               case 280:
                  if (curChar == 88)
                     jjCheckNAdd(279);
                  break;
               case 282:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(409, 412);
                  break;
               case 289:
                  if (curChar == 120)
                     jjCheckNAdd(290);
                  break;
               case 290:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(268, 271);
                  break;
               case 291:
                  if (curChar == 88)
                     jjCheckNAdd(290);
                  break;
               case 293:
                  if (curChar == 120)
                     jjCheckNAdd(294);
                  break;
               case 294:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(280, 283);
                  break;
               case 295:
                  if (curChar == 88)
                     jjCheckNAdd(294);
                  break;
               case 296:
                  if (curChar == 120)
                     jjCheckNAdd(297);
                  break;
               case 297:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(297, 252);
                  break;
               case 298:
                  if (curChar == 88)
                     jjCheckNAdd(297);
                  break;
               case 299:
                  if (curChar == 120)
                     jjCheckNAdd(300);
                  break;
               case 300:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(300, 272);
                  break;
               case 301:
                  if (curChar == 88)
                     jjCheckNAdd(300);
                  break;
               case 302:
                  if (curChar == 120)
                     jjCheckNAdd(303);
                  break;
               case 303:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(303, 282);
                  break;
               case 304:
                  if (curChar == 88)
                     jjCheckNAdd(303);
                  break;
               case 313:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(413, 416);
                  break;
               case 320:
                  if (curChar == 120)
                     jjCheckNAdd(321);
                  break;
               case 321:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(302, 304);
                  break;
               case 322:
                  if (curChar == 88)
                     jjCheckNAdd(321);
                  break;
               case 326:
                  if (curChar == 120)
                     jjCheckNAdd(327);
                  break;
               case 327:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(327, 313);
                  break;
               case 328:
                  if (curChar == 88)
                     jjCheckNAdd(327);
                  break;
               case 336:
                  if (curChar == 120)
                     jjCheckNAdd(337);
                  break;
               case 337:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(318, 320);
                  break;
               case 338:
                  if (curChar == 88)
                     jjCheckNAdd(337);
                  break;
               case 340:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(417, 420);
                  break;
               case 347:
                  if (curChar == 120)
                     jjCheckNAdd(348);
                  break;
               case 348:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(332, 334);
                  break;
               case 349:
                  if (curChar == 88)
                     jjCheckNAdd(348);
                  break;
               case 352:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(421, 424);
                  break;
               case 359:
                  if (curChar == 120)
                     jjCheckNAdd(360);
                  break;
               case 360:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(360);
                  break;
               case 361:
                  if (curChar == 88)
                     jjCheckNAdd(360);
                  break;
               case 369:
                  if (curChar == 120)
                     jjCheckNAdd(370);
                  break;
               case 370:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(370);
                  break;
               case 371:
                  if (curChar == 88)
                     jjCheckNAdd(370);
                  break;
               case 376:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(425, 428);
                  break;
               case 383:
                  if (curChar == 120)
                     jjCheckNAdd(384);
                  break;
               case 384:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(384);
                  break;
               case 385:
                  if (curChar == 88)
                     jjCheckNAdd(384);
                  break;
               case 389:
                  if (curChar == 120)
                     jjCheckNAdd(390);
                  break;
               case 390:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(390, 376);
                  break;
               case 391:
                  if (curChar == 88)
                     jjCheckNAdd(390);
                  break;
               case 403:
                  if (curChar == 120)
                     jjCheckNAdd(404);
                  break;
               case 404:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(358, 360);
                  break;
               case 405:
                  if (curChar == 88)
                     jjCheckNAdd(404);
                  break;
               case 406:
                  if (curChar == 120)
                     jjCheckNAdd(407);
                  break;
               case 407:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(407, 310);
                  break;
               case 408:
                  if (curChar == 88)
                     jjCheckNAdd(407);
                  break;
               case 409:
                  if (curChar == 120)
                     jjCheckNAdd(410);
                  break;
               case 410:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(410, 330);
                  break;
               case 411:
                  if (curChar == 88)
                     jjCheckNAdd(410);
                  break;
               case 412:
                  if (curChar == 120)
                     jjCheckNAdd(413);
                  break;
               case 413:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(413, 340);
                  break;
               case 414:
                  if (curChar == 88)
                     jjCheckNAdd(413);
                  break;
               case 415:
                  if (curChar == 120)
                     jjCheckNAdd(416);
                  break;
               case 416:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(416);
                  break;
               case 417:
                  if (curChar == 88)
                     jjCheckNAdd(416);
                  break;
               case 418:
                  if (curChar == 120)
                     jjCheckNAdd(419);
                  break;
               case 419:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(419, 352);
                  break;
               case 420:
                  if (curChar == 88)
                     jjCheckNAdd(419);
                  break;
               case 421:
                  if (curChar == 120)
                     jjCheckNAdd(422);
                  break;
               case 422:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(422, 363);
                  break;
               case 423:
                  if (curChar == 88)
                     jjCheckNAdd(422);
                  break;
               case 424:
                  if (curChar == 120)
                     jjCheckNAdd(425);
                  break;
               case 425:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(425, 373);
                  break;
               case 426:
                  if (curChar == 88)
                     jjCheckNAdd(425);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 31:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(395, 396);
                  break;
               case 238:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 427 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x20L);
      default :
         return 1;
   }
}
static private int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(1, 5);
         break;
      default :
         return 2;
   }
   return 2;
}
static final int[] jjnextStates = {
   237, 241, 243, 309, 310, 329, 330, 339, 340, 244, 248, 350, 351, 352, 362, 363, 
   372, 373, 403, 405, 406, 408, 409, 411, 412, 414, 415, 417, 418, 420, 421, 423, 
   424, 426, 393, 394, 310, 395, 330, 396, 340, 244, 248, 397, 398, 352, 399, 363, 
   400, 373, 169, 170, 171, 174, 183, 189, 171, 172, 173, 174, 183, 189, 171, 175, 
   176, 232, 186, 233, 198, 234, 173, 174, 183, 189, 177, 226, 228, 181, 220, 222, 
   171, 182, 173, 174, 183, 189, 171, 184, 176, 185, 186, 218, 198, 219, 173, 174, 
   183, 189, 187, 212, 214, 171, 188, 173, 174, 183, 189, 190, 192, 193, 195, 196, 
   208, 209, 211, 200, 202, 204, 171, 201, 173, 174, 183, 189, 171, 203, 173, 174, 
   183, 189, 205, 207, 171, 206, 173, 174, 183, 189, 171, 210, 173, 174, 183, 189, 
   171, 213, 173, 174, 183, 189, 215, 217, 171, 216, 173, 174, 183, 189, 171, 219, 
   173, 174, 183, 189, 171, 221, 173, 174, 183, 189, 223, 225, 171, 224, 173, 174, 
   183, 189, 229, 231, 171, 234, 173, 174, 183, 189, 243, 244, 248, 245, 247, 292, 
   244, 248, 305, 306, 252, 307, 272, 308, 282, 250, 244, 248, 249, 251, 252, 271, 
   272, 281, 282, 250, 244, 248, 249, 250, 253, 265, 267, 257, 259, 261, 244, 248, 
   258, 250, 244, 248, 260, 250, 262, 264, 244, 248, 263, 250, 268, 270, 273, 275, 
   277, 244, 248, 274, 250, 244, 248, 276, 250, 278, 280, 244, 248, 279, 250, 284, 
   286, 288, 244, 248, 285, 250, 244, 248, 287, 250, 289, 291, 244, 248, 290, 250, 
   293, 295, 296, 298, 299, 301, 302, 304, 244, 248, 294, 250, 244, 248, 305, 250, 
   311, 323, 325, 315, 317, 319, 316, 244, 248, 318, 244, 248, 320, 322, 321, 244, 
   248, 326, 328, 331, 333, 335, 332, 244, 248, 334, 244, 248, 336, 338, 337, 244, 
   248, 342, 344, 346, 343, 244, 248, 345, 244, 248, 347, 349, 348, 244, 248, 354, 
   356, 358, 359, 361, 364, 366, 368, 369, 371, 374, 386, 388, 378, 380, 382, 383, 
   385, 389, 391, 393, 244, 248, 404, 244, 248, 169, 170, 235, 40, 47, 56, 161, 
   167, 152, 158, 125, 130, 134, 139, 143, 148, 111, 117, 121, 18, 103, 104, 97, 
   98, 85, 88, 93, 78, 2, 82, 59, 62, 66, 72, 31, 32, 180, 181, 220, 
   222, 199, 200, 202, 204, 256, 257, 259, 261, 283, 284, 286, 288, 314, 315, 317, 
   319, 341, 342, 344, 346, 353, 354, 356, 358, 377, 378, 380, 382, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, "\57\52", "\52\57", null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\53", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "INSIDE_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, 1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, 
};
static final long[] jjtoToken = {
   0x4097ffdL, 
};
static final long[] jjtoSkip = {
   0x2L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[427];
static private final int[] jjstateSet = new int[854];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public Proj6TokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public Proj6TokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 427; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 6)
       {
          jjmatchedKind = 6;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 2 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
           debugStream.println("EXPRESSION: " + matchedToken.image);
         break;
      case 3 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
            debugStream.println("ASSIGNMENT STATEMENT: " + matchedToken.image);
         break;
      case 9 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        debugStream.println("RESERVED token: " + matchedToken.image);
         break;
      case 10 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        debugStream.println("STRING: " + matchedToken.image);
         break;
      case 11 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          debugStream.println("INTEGER: " + matchedToken.image);
         break;
      case 12 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          debugStream.println("REAL: " + matchedToken.image);
         break;
      case 13 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          debugStream.println("CHAR: " + matchedToken.image);
         break;
      case 14 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        debugStream.println("Identifier: " + matchedToken.image);
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
