/* Generated By:JavaCC: Do not edit this line. Proj6TokenManager.java */
package project6;
import java.io.*;

/** Token Manager. */
public class Proj6TokenManager implements Proj6Constants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x4L) != 0L)
         {
            jjmatchedKind = 8;
            return 1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 47:
         return jjMoveStringLiteralDfa1_0(0x4L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(1, 2, 2);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 260;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xfc00ffee00000000L & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 14)
                        kind = 14;
                     jjCheckNAdd(246);
                  }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddStates(0, 6);
                  }
                  else if ((0x100100002400L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if (curChar == 48)
                     jjAddStates(7, 14);
                  else if (curChar == 43)
                     jjCheckNAddTwoStates(38, 65);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(38, 63);
                  else if (curChar == 38)
                     jjCheckNAddTwoStates(59, 38);
                  else if (curChar == 60)
                     jjCheckNAddStates(15, 17);
                  else if (curChar == 62)
                     jjCheckNAddStates(18, 20);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 48;
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 45;
                  else if (curChar == 61)
                     jjCheckNAdd(38);
                  else if (curChar == 37)
                     jjCheckNAdd(38);
                  else if (curChar == 33)
                     jjCheckNAdd(38);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(35, 36);
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if (curChar == 48)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddStates(21, 27);
                  }
                  break;
               case 1:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 3:
                  if (curChar == 47 && kind > 5)
                     kind = 5;
                  break;
               case 4:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 34:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(35, 36);
                  break;
               case 35:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(35, 36);
                  break;
               case 36:
                  if (curChar == 34 && kind > 7)
                     kind = 7;
                  break;
               case 37:
                  if ((0xfc00ffee00000000L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 38:
                  if (curChar == 61 && kind > 8)
                     kind = 8;
                  break;
               case 39:
                  if (curChar == 33)
                     jjCheckNAdd(38);
                  break;
               case 41:
                  if (curChar == 37)
                     jjCheckNAdd(38);
                  break;
               case 42:
                  if (curChar == 61)
                     jjCheckNAdd(38);
                  break;
               case 43:
                  if (curChar == 47)
                     jjCheckNAdd(38);
                  break;
               case 44:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 49:
                  if (curChar == 39 && kind > 11)
                     kind = 11;
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 52:
                  if (curChar == 62)
                     jjCheckNAddStates(18, 20);
                  break;
               case 53:
                  if (curChar == 62)
                     jjCheckNAdd(38);
                  break;
               case 54:
                  if (curChar == 62 && kind > 8)
                     kind = 8;
                  break;
               case 55:
                  if (curChar == 60)
                     jjCheckNAddStates(15, 17);
                  break;
               case 56:
                  if (curChar == 60)
                     jjCheckNAdd(38);
                  break;
               case 57:
                  if (curChar == 60 && kind > 8)
                     kind = 8;
                  break;
               case 58:
                  if (curChar == 38)
                     jjCheckNAddTwoStates(59, 38);
                  break;
               case 59:
                  if (curChar == 38 && kind > 8)
                     kind = 8;
                  break;
               case 62:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(38, 63);
                  break;
               case 63:
                  if (curChar == 45 && kind > 8)
                     kind = 8;
                  break;
               case 64:
                  if (curChar == 43)
                     jjCheckNAddTwoStates(38, 65);
                  break;
               case 65:
                  if (curChar == 43 && kind > 8)
                     kind = 8;
                  break;
               case 198:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(0, 6);
                  break;
               case 199:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(199);
                  break;
               case 200:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(200, 201);
                  break;
               case 202:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(28, 30);
                  break;
               case 203:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(204);
                  break;
               case 204:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(204);
                  break;
               case 205:
                  if (curChar != 48)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(206);
                  break;
               case 206:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(206);
                  break;
               case 207:
                  if (curChar == 48)
                     jjAddStates(31, 32);
                  break;
               case 209:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(211, 212);
                  break;
               case 212:
                  if (curChar == 46)
                     jjAddStates(33, 35);
                  break;
               case 213:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(214);
                  break;
               case 214:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(214);
                  break;
               case 215:
                  if (curChar != 48)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(216);
                  break;
               case 216:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(216);
                  break;
               case 217:
                  if (curChar == 48)
                     jjAddStates(36, 37);
                  break;
               case 219:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(221, 222);
                  break;
               case 222:
                  if (curChar == 46)
                     jjAddStates(38, 40);
                  break;
               case 223:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(224, 225);
                  break;
               case 224:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(224, 225);
                  break;
               case 226:
                  if ((0x280000000000L & l) != 0L)
                     jjAddStates(41, 43);
                  break;
               case 227:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(228);
                  break;
               case 228:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(228);
                  break;
               case 229:
                  if (curChar != 48)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(230);
                  break;
               case 230:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(230);
                  break;
               case 231:
                  if (curChar == 48)
                     jjAddStates(44, 45);
                  break;
               case 233:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(236, 225);
                  break;
               case 236:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(236, 225);
                  break;
               case 237:
                  if (curChar == 48)
                     jjAddStates(46, 47);
                  break;
               case 239:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(239, 225);
                  break;
               case 241:
                  if (curChar != 48)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(21, 27);
                  break;
               case 242:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(242);
                  break;
               case 243:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(243, 201);
                  break;
               case 244:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(244, 212);
                  break;
               case 245:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(245, 222);
                  break;
               case 246:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(246);
                  break;
               case 247:
                  if (curChar == 48)
                     jjAddStates(7, 14);
                  break;
               case 249:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 252:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(252, 201);
                  break;
               case 255:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(255, 212);
                  break;
               case 258:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(258, 222);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjCheckNAdd(51);
                  }
                  else if ((0x7800000068000001L & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  else if (curChar == 95)
                     jjAddStates(48, 50);
                  if (curChar == 118)
                     jjAddStates(51, 52);
                  else if (curChar == 117)
                     jjAddStates(53, 54);
                  else if (curChar == 115)
                     jjAddStates(55, 60);
                  else if (curChar == 114)
                     jjAddStates(61, 63);
                  else if (curChar == 105)
                     jjCheckNAddStates(64, 66);
                  else if (curChar == 102)
                     jjAddStates(67, 68);
                  else if (curChar == 101)
                     jjAddStates(69, 71);
                  else if (curChar == 100)
                     jjCheckNAddStates(72, 74);
                  else if (curChar == 99)
                     jjAddStates(75, 78);
                  else if (curChar == 124)
                     jjCheckNAddTwoStates(61, 38);
                  else if (curChar == 94)
                     jjCheckNAdd(38);
                  else if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 2:
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 111 && kind > 6)
                     kind = 6;
                  break;
               case 7:
               case 15:
                  if (curChar == 116)
                     jjCheckNAdd(6);
                  break;
               case 8:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 107 && kind > 6)
                     kind = 6;
                  break;
               case 11:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 16:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 103 && kind > 6)
                     kind = 6;
                  break;
               case 19:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 102 && kind > 6)
                     kind = 6;
                  break;
               case 23:
                  if (curChar == 101)
                     jjCheckNAdd(22);
                  break;
               case 24:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 101 && kind > 6)
                     kind = 6;
                  break;
               case 30:
               case 109:
               case 192:
                  if (curChar == 108)
                     jjCheckNAdd(29);
                  break;
               case 31:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 35:
                  jjAddStates(79, 80);
                  break;
               case 37:
                  if ((0x7800000068000001L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 40:
                  if (curChar == 94)
                     jjCheckNAdd(38);
                  break;
               case 48:
                  if ((0x7fffffe17fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 50:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(51);
                  break;
               case 51:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(51);
                  break;
               case 60:
                  if (curChar == 124)
                     jjCheckNAddTwoStates(61, 38);
                  break;
               case 61:
                  if (curChar == 124 && kind > 8)
                     kind = 8;
                  break;
               case 66:
                  if (curChar == 95)
                     jjAddStates(48, 50);
                  break;
               case 67:
                  if (curChar == 108 && kind > 6)
                     kind = 6;
                  break;
               case 68:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 120 && kind > 6)
                     kind = 6;
                  break;
               case 72:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 121 && kind > 6)
                     kind = 6;
                  break;
               case 79:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 99)
                     jjAddStates(75, 78);
                  break;
               case 88:
               case 114:
                  if (curChar == 115)
                     jjCheckNAdd(29);
                  break;
               case 89:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 114 && kind > 6)
                     kind = 6;
                  break;
               case 91:
                  if (curChar == 97)
                     jjCheckNAdd(90);
                  break;
               case 92:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 116 && kind > 6)
                     kind = 6;
                  break;
               case 94:
                  if (curChar == 115)
                     jjCheckNAdd(93);
                  break;
               case 95:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 117)
                     jjCheckNAdd(29);
                  break;
               case 98:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 100)
                     jjCheckNAddStates(72, 74);
                  break;
               case 104:
                  if (curChar == 108)
                     jjCheckNAdd(93);
                  break;
               case 105:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 110:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if (curChar == 101)
                     jjAddStates(69, 71);
                  break;
               case 115:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 109 && kind > 6)
                     kind = 6;
                  break;
               case 117:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 110 && kind > 6)
                     kind = 6;
                  break;
               case 120:
               case 148:
                  if (curChar == 114)
                     jjCheckNAdd(119);
                  break;
               case 121:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 102)
                     jjAddStates(67, 68);
                  break;
               case 125:
                  if (curChar == 97)
                     jjCheckNAdd(93);
                  break;
               case 126:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 111)
                     jjCheckNAdd(90);
                  break;
               case 129:
                  if (curChar == 105)
                     jjCheckNAddStates(64, 66);
                  break;
               case 130:
                  if (curChar == 110)
                     jjCheckNAdd(29);
                  break;
               case 131:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 110)
                     jjCheckNAdd(93);
                  break;
               case 135:
                  if (curChar == 114)
                     jjAddStates(61, 63);
                  break;
               case 136:
                  if (curChar == 101)
                     jjCheckNAdd(90);
                  break;
               case 137:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
               case 170:
                  if (curChar == 99)
                     jjCheckNAdd(93);
                  break;
               case 143:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 149:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 115)
                     jjAddStates(55, 60);
                  break;
               case 153:
                  if (curChar == 114)
                     jjCheckNAdd(93);
                  break;
               case 154:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 100 && kind > 6)
                     kind = 6;
                  break;
               case 157:
               case 183:
                  if (curChar == 101)
                     jjCheckNAdd(156);
                  break;
               case 158:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 111)
                     jjCheckNAdd(22);
                  break;
               case 162:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 99 && kind > 6)
                     kind = 6;
                  break;
               case 166:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 171:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 172:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 104 && kind > 6)
                     kind = 6;
                  break;
               case 175:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 117)
                     jjAddStates(53, 54);
                  break;
               case 180:
                  if (curChar == 111)
                     jjCheckNAdd(119);
                  break;
               case 181:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 182:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 184:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 188:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 189:
                  if (curChar == 118)
                     jjAddStates(51, 52);
                  break;
               case 190:
                  if (curChar == 105)
                     jjCheckNAdd(156);
                  break;
               case 191:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 193:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 194:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 201:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(81, 84);
                  break;
               case 208:
                  if (curChar == 120)
                     jjCheckNAdd(209);
                  break;
               case 209:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(209);
                  break;
               case 210:
                  if (curChar == 88)
                     jjCheckNAdd(209);
                  break;
               case 218:
                  if (curChar == 120)
                     jjCheckNAdd(219);
                  break;
               case 219:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(219);
                  break;
               case 220:
                  if (curChar == 88)
                     jjCheckNAdd(219);
                  break;
               case 225:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(85, 88);
                  break;
               case 232:
                  if (curChar == 120)
                     jjCheckNAdd(233);
                  break;
               case 233:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(233);
                  break;
               case 234:
                  if (curChar == 88)
                     jjCheckNAdd(233);
                  break;
               case 238:
                  if (curChar == 120)
                     jjCheckNAdd(239);
                  break;
               case 239:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(239, 225);
                  break;
               case 240:
                  if (curChar == 88)
                     jjCheckNAdd(239);
                  break;
               case 248:
                  if (curChar == 120)
                     jjCheckNAdd(249);
                  break;
               case 249:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(249);
                  break;
               case 250:
                  if (curChar == 88)
                     jjCheckNAdd(249);
                  break;
               case 251:
                  if (curChar == 120)
                     jjCheckNAdd(252);
                  break;
               case 252:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(252, 201);
                  break;
               case 253:
                  if (curChar == 88)
                     jjCheckNAdd(252);
                  break;
               case 254:
                  if (curChar == 120)
                     jjCheckNAdd(255);
                  break;
               case 255:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(255, 212);
                  break;
               case 256:
                  if (curChar == 88)
                     jjCheckNAdd(255);
                  break;
               case 257:
                  if (curChar == 120)
                     jjCheckNAdd(258);
                  break;
               case 258:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(258, 222);
                  break;
               case 259:
                  if (curChar == 88)
                     jjCheckNAdd(258);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 35:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(79, 80);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 260 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x8L);
      default :
         return 1;
   }
}
static private int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(1, 3);
         break;
      default :
         return 2;
   }
   return 2;
}
static final int[] jjnextStates = {
   199, 200, 201, 211, 212, 221, 222, 248, 250, 251, 253, 254, 256, 257, 259, 56, 
   38, 57, 53, 38, 54, 242, 243, 201, 244, 212, 245, 222, 203, 205, 207, 208, 
   210, 213, 215, 217, 218, 220, 223, 235, 237, 227, 229, 231, 232, 234, 238, 240, 
   70, 77, 86, 191, 197, 182, 188, 155, 160, 164, 169, 173, 178, 141, 147, 151, 
   22, 133, 134, 127, 128, 115, 118, 123, 108, 6, 112, 89, 92, 96, 102, 35, 
   36, 202, 203, 205, 207, 226, 227, 229, 231, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, "\57\52", "\52\57", null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "INSIDE_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, 1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x25ffdL, 
};
static final long[] jjtoSkip = {
   0x2L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[260];
static private final int[] jjstateSet = new int[520];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public Proj6TokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public Proj6TokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 260; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 4)
       {
          jjmatchedKind = 4;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 6 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        debugStream.println("RESERVED token: " + matchedToken.image);
         break;
      case 7 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        debugStream.println("STRING: " + matchedToken.image);
         break;
      case 8 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        debugStream.println("Special Symbol: " + matchedToken.image);
         break;
      case 9 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          debugStream.println("INTEGER: " + matchedToken.image);
         break;
      case 10 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          debugStream.println("REAL: " + matchedToken.image);
         break;
      case 11 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          debugStream.println("CHAR: " + matchedToken.image);
         break;
      case 12 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        debugStream.println("Identifier: " + matchedToken.image);
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
