/* Generated By:JavaCC: Do not edit this line. Proj6TreeConstants.java Version 5.0 */
package project6;

public interface Proj6TreeConstants
{
  public int JJTASSIGNMENT = 0;
  public int JJTOPERAND = 1;
  public int JJTNUMBER = 2;


  public String[] jjtNodeName = {
    "Assignment",
    "Operand",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=d78cff33d44d29bbfd82c8eda539650e (do not edit this line) */
