/* Generated By:JavaCC: Do not edit this line. Proj6Constants.java */
package project6;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Proj6Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IGNORE = 1;
  /** RegularExpression Id. */
  int EXPRESSION = 2;
  /** RegularExpression Id. */
  int ASSIGNMENT_STATEMENT = 3;
  /** RegularExpression Id. */
  int MULT_COMMENT = 7;
  /** RegularExpression Id. */
  int MATH_SYMBOL = 8;
  /** RegularExpression Id. */
  int RESERVED = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int REAL = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int UPPER = 15;
  /** RegularExpression Id. */
  int DIGITS = 16;
  /** RegularExpression Id. */
  int LOWER = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int DECIMAL = 20;
  /** RegularExpression Id. */
  int OCTAL = 21;
  /** RegularExpression Id. */
  int HEXIDECIMAL = 22;
  /** RegularExpression Id. */
  int NODEC = 23;
  /** RegularExpression Id. */
  int NOEXP = 24;
  /** RegularExpression Id. */
  int BOTH = 25;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSIDE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IGNORE>",
    "<EXPRESSION>",
    "<ASSIGNMENT_STATEMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 6>",
    "<MULT_COMMENT>",
    "<MATH_SYMBOL>",
    "<RESERVED>",
    "<STRING>",
    "<INTEGER>",
    "<REAL>",
    "<CHAR>",
    "<IDENTIFIER>",
    "<UPPER>",
    "<DIGITS>",
    "<LOWER>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL>",
    "<OCTAL>",
    "<HEXIDECIMAL>",
    "<NODEC>",
    "<NOEXP>",
    "<BOTH>",
    "\"+\"",
  };

}
